Args=--initialize-at-build-time=com.taoensso.telemere.slf4j.TelemereLogger \
     --initialize-at-build-time=com.taoensso.telemere.slf4j.TelemereLoggerFactory \
     --initialize-at-build-time=com.taoensso.telemere.slf4j.TelemereServiceProvider \
     --initialize-at-build-time=org.slf4j.helpers.BasicMDCAdapter \
     --initialize-at-build-time=org.slf4j.helpers.BasicMDCAdapter$1
